name: Build ISO

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build cross-compiler container
        run: make docker-build

      - name: Build ISO inside container
        run: docker run --rm -v ${{ github.workspace }}:/var/lib/deados deados_builder bash -c "cd /var/lib/deados && make"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: deados.iso
          path: deados.iso
